xcopy ".\Tap.ERP.Api.deps.json" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Api.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Api.exe" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Api.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Bank.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Bank.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Base.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Base.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Cash.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Cash.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Catalogs.Core.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Catalogs.Core.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Catalogs.SckGdsCg.SckGdsPn.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Catalogs.SckGdsCg.SckGdsPn.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Catalogs.WebCore.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Catalogs.WebCore.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Core.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Core.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.DbContext.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.DbContext.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Entities.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Entities.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Finance.FinAcc.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Finance.FinAcc.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Models.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Models.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Payment.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Payment.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Pos.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Pos.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.GenCurPr.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.GenCurPr.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.GoodsOverAdd.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.GoodsOverAdd.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.GoodsPrice.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.GoodsPrice.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.ModVchPayment.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.ModVchPayment.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.OverAdd.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.OverAdd.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.SalModPayment.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.SalModPayment.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.ServicePrice.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.ServicePrice.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Sale.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.SaleTax.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.SaleTax.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Services.Core.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Services.Core.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Services.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Services.pdb" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Stock.dll" "d:\2\" /Q/Y
xcopy ".\Tap.ERP.Stock.pdb" "d:\2\" /Q/Y
xcopy ".\appsettings.Development.json" "d:\2\" /Q/Y
xcopy ".\appsettings.Production.json" "d:\2\" /Q/Y
xcopy ".\appsettings.json" "d:\2\" /Q/Y